### ISSUE TITLE
Change random token when upload data to firebase

### ISSUE THREAD

**Issue by ChiHangChen** [Kohze/fireData#13]
There is always a random token such like "-LPfvzUEo8jkeAU56K2e" when I upload data to firebase database, is there any ways to change that?

[Example](https://imgur.com/jn11snC)

**Comment by ChiHangChen** [comment]
Sorry, I found out that use "patch" function can achieve that.

**Comment by RojoDiego** [comment]
How do you do that? The documentation is a little barebones and hard to understand.

**Comment by ChiHangChen** [comment]
I'm not so sure since it is almost one and half year ago, maybe try using path with specific file name : 
`patch(x = mtcars, projectURL = "https://firedata-b0e54.firebaseio.com/", directory = "main/filename")`
