### ISSUE TITLE
No data appears in Firebase

### ISSUE THREAD

**Issue by hack-r** [Kohze/fireData#19]
Hi, this is an awesome and much needed package! 

I'm having trouble with the upload. I tried it with and without a collection pre-defined ahead of time matching the data structure. No errors and the authentication succeeded. 

```
if (!require("devtools")) install.packages("devtools")
devtools::install_github("Kohze/fireData")

library(fireData)

token <- anonymous_login(project_api = "sdfsdsds")
token

token$idToken

data(mtcars)
upload(x          = mtcars, 
       projectURL = "https://afafer-asas.firebaseio.com/", 
       directory  = "testing123")
```

**Comment by hack-r** [comment]
It started working... I'm not actually sure what I did that made it go from not working for hours to working... 

The only thing I know of that I did was to switch the dropdown menu from "Cloud Firestore" to "Real-time DB" in the cloud...

**Comment by Kohze** [comment]
the functions indeed are working with the realtime db but not cloud firestore - we had a fork and gsoc project specifically implementing cloud firestore, but even now the REST API for cloud firestore is limited compared to the real time database.
