### ISSUE TITLE
Different classes on Realtime Database

### ISSUE THREAD

**Issue by rsilveirafh** [Kohze/fireData#24]
Hello Kohze.
Thanks for the great package. To work with it I had to make some minor changes, but in general, everything is working very good.

I have an issue after uploading data to realtime database: I need the variable to be _true_ (Java logical), and it always return _"true"_ (R character class). I have tried: changing the class to logical R (_TRUE_), factor R (level _true_), but none of them worked.

How it is:
![image](https://user-images.githubusercontent.com/8616924/88721505-f04aee80-d0fc-11ea-981d-273b40eeaf31.png)

How I want:
![image](https://user-images.githubusercontent.com/8616924/88721553-ffca3780-d0fc-11ea-91b9-4153f5b9e41d.png)

Do you know how can I do this through R?

Thanks a lot!

R.

**Comment by rsilveirafh** [comment]
I did it!

**Comment by Kohze** [comment]
please add your solution to this post that the next one with the same issues knows how to solve it :)

**Comment by rsilveirafh** [comment]
> please add your solution to this post that the next one with the same issues knows how to solve it :)

Sure! Thanks for remembering me this.
