### ISSUE TITLE
Google FireStore upload

### ISSUE THREAD

**Issue by EnzleDev** [Kohze/FireData#27]
Hello! I was wondering if there was a way to upload into the FireStore component of Firebase rather than the Realtime Database portion? I am using this package to automate data upload into the realtime database but also would like to upload data into the FireStore as well.

**Comment by Kohze** [comment]
there is a fork that can interact with cloud firestore:

https://github.com/owninz/fireData

**Comment by EnzleAnalytics** [comment]
Thank you so much! I'm a huge fan of this package, it's been great for me to establish a data-upload workflow that feeds into my mobile app. Thank you again for the quick response and the work you've done on this!
