### ISSUE TITLE
Interested in status of this project

### ISSUE THREAD

**Issue by peeyooshc** [Kohze/fireData#4]
Hi there,

 I'm interested in knowing the status of this project. Wanting to connect to a Firebase DB and came across your project. Trying to decide if I roll my own or adopt your framework which looks good and provides the basic functionality I'm after.

 Thanks in advance,
 PC

**Comment by Kohze** [comment]
Hallo,

Great that you found some interest, It will have a first version completed within 10 days from now. In the meantime you could also just take the index.R and copy the code you need for your firebase connection.

**Comment by Kohze** [comment]
We now got pretty much the basic functionality included (fixed some last bugs today). In case you want to contribute to add more functionality, let me know.
