### ISSUE TITLE
Access data without Firebase Database

### ISSUE THREAD

**Issue by ganesh3** [Kohze/fireData#7]
Hi,

Would like to know how can we access data from Firebase if we are not storing data in the database?

We do not use the database currently and hence the projectURL and fileName parameter cannot be provided.

Regards
Ganesh Bhat

**Comment by Kohze** [comment]
Can you specify a bit what data you are actually trying to access if your database has no data? 
I assume you mean that someone uploaded something but you dont have that exact URL, in that case you can always download the full path or even full database (then you will get a list object back). If you give me a bit more details about the problem to solve I can certainly provide some code for that.

**Comment by ganesh3** [comment]
Hi,

Let me give you a background:

I have 1 app for basic functionality which is deployed on Android Play Store & iOS App Store. I am  tracking analytics using Google Analytics & Firebase.

Within Firebase I am tracking EVENTS and I want to access the events data that is visible on the Firebase Console. There is 1 project within firebase and 2 sub project i.e. one for Android measurement and one for iOS. We are able to view the event related data on the Firebase UI which we want to access.

On clicking Database on firebase UI, I do not have any database to access data from whereas Firebase is still reporting the data. How do I access the data that Firebase is reporting and access it via Firedata within R?


Regards
Ganesh Bhat

**Comment by Kohze** [comment]
I guess then your question is related to https://firebase.google.com/docs/analytics/ where they mention Bigquery as only option to store those firebase console data. 

> If you need to perform custom analysis or join your data with other sources you can link your Analytics data to BigQuery, which allows for more complex analysis like querying large data sets and joining multiple data sources.

BigQuery is a SQL database in the google cloud, and there is also a R package for it in case you want to access your event data. Other than that it could be joined with firebase cloud functions where you might be able to just write something that puts the events into the firebase DB, but I guess that is the more difficult route unless you know how to write firebase cloud functions.
